### ISSUE TITLE
Unable to load tasks/google_authenticator.rake

### ISSUE THREAD

**Issue by johan-smits** [jaredonline/google-authenticator#46]
Since version **1.5.0** and also **1.6.0** it is not possible to load the file during assets precompile:

```
$ bin/rails assets:precompile RAILS_ENV=production
rails aborted!
LoadError: cannot load such file -- tasks/google_authenticator.rake
/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `load'
/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `block in load'
/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `load'
/vendor/bundle/ruby/2.3.0/gems/google-authenticator-rails-1.5.0/lib/google-authenticator-rails.rb:32:in `block in <class:Railtie>'
/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/railtie.rb:246:in `instance_exec'
/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/railtie.rb:246:in `block in run_tasks_blocks'
/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/railtie.rb:255:in `each'
/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/railtie.rb:255:in `each_registered_block'
/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/railtie.rb:246:in `run_tasks_blocks'
/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/application.rb:514:in `block in run_tasks_blocks'
/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/engine/railties.rb:15:in `each'
/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/engine/railties.rb:15:in `each'
/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/application.rb:514:in `run_tasks_blocks'
/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/engine.rb:459:in `load_tasks'
/Rakefile:6:in `<top (required)>'
/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:22:in `block in perform'
/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/command.rb:48:in `invoke'
/vendor/bundle/ruby/2.3.0/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
```

I use it with Rails **5.2.0**.

The **1.4.1** version works ok. What changes are done of what can I do to give better feedback?

**Comment by johan-smits** [comment]
@jaredonline @Tietew thnx, that worked!
For me the 1.5.1 is not needed, I'll go for the 1.6.1.
